[package]
name = "persistent-homology"
version = "0.1.0"
edition = "2024"

description = "A Rust library for computing persistent homology."
license = "MIT"

[lib]
name = "persistent_homology"
path = "src/lib.rs"


[dependencies]
itertools = "0.15"
rand = "0.10.2"
csv = "1.4"
nalgebra = "0.35"

[dev-dependencies]
plotters = "0.3.3"
